version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./dreambooth_model_disney:/app/dreambooth_model_disney
    environment:
      - MODEL_PATH=/app/dreambooth_model_disney
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
